// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentAPI.Data;

namespace PaymentAPI.Migrations
{
    [DbContext(typeof(CPGContext))]
    [Migration("20200301213843_addedNewIdForBankPaymentResponse")]
    partial class addedNewIdForBankPaymentResponse
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PaymentAPI.Models.BankPaymentResponse", b =>
                {
                    b.Property<int>("BankPaymentResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MerchantId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentRequestId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("BankPaymentResponseId");

                    b.HasIndex("MerchantId");

                    b.HasIndex("PaymentRequestId")
                        .IsUnique();

                    b.ToTable("BankPaymentResponses");
                });

            modelBuilder.Entity("PaymentAPI.Models.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MerchantId")
                        .HasColumnType("int");

                    b.Property<string>("card_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<string>("currency")
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("cvv")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<int>("expiry_month")
                        .HasColumnType("int");

                    b.Property<int>("expiry_year")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardId");

                    b.HasIndex("MerchantId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("PaymentAPI.Models.Merchant", b =>
                {
                    b.Property<int>("MerchantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaxAmount")
                        .HasColumnType("int");

                    b.Property<int>("MinAmount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MerchantId");

                    b.ToTable("Merchants");
                });

            modelBuilder.Entity("PaymentAPI.Models.PaymentRequest", b =>
                {
                    b.Property<int>("PaymentRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("MerchantId")
                        .HasColumnType("int");

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("capture_on")
                        .HasColumnType("datetime2");

                    b.Property<string>("currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentRequestId");

                    b.HasIndex("CardId")
                        .IsUnique();

                    b.HasIndex("MerchantId");

                    b.ToTable("PaymentRequests");
                });

            modelBuilder.Entity("PaymentAPI.Models.BankPaymentResponse", b =>
                {
                    b.HasOne("PaymentAPI.Models.Merchant", null)
                        .WithMany("BankPaymentResponses")
                        .HasForeignKey("MerchantId");

                    b.HasOne("PaymentAPI.Models.PaymentRequest", "PaymentRequest")
                        .WithOne("Status")
                        .HasForeignKey("PaymentAPI.Models.BankPaymentResponse", "PaymentRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PaymentAPI.Models.Card", b =>
                {
                    b.HasOne("PaymentAPI.Models.Merchant", "Merchant")
                        .WithMany("Cards")
                        .HasForeignKey("MerchantId");
                });

            modelBuilder.Entity("PaymentAPI.Models.PaymentRequest", b =>
                {
                    b.HasOne("PaymentAPI.Models.Card", "Card")
                        .WithOne("PaymentRequest")
                        .HasForeignKey("PaymentAPI.Models.PaymentRequest", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PaymentAPI.Models.Merchant", "Merchant")
                        .WithMany("PaymentRequests")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
